language: c
compiler: gcc
sudo: false
cache: ccache
os: linux

matrix:
  include:
    - dist: xenial
    - dist: bionic
    - dist: focal
    - dist: jammy

script:
  - make lib programs
  - tests/ssl-opt.sh -f 'Fallback SCSV.*list'

after_failure:
- tests/scripts/travis-log-failure.sh
