language: c
compiler: gcc
sudo: false
cache: ccache

jobs:
  include:
    - name: macOS
      os: osx
      compiler: clang
      script:
        - tests/scripts/all.sh -k test_default_out_of_box

    - name: Windows
      os: windows
      before_install:
        - choco install strawberryperl
        - choco install python --version=3.5.4
      env:
        # Add the directory where the Choco packages go
        - PATH=/c/Python35:/c/Python35/Scripts:/c/Strawberry:$PATH
      script:
        - type perl; perl --version
        - type python; python --version
        - scripts/make_generated_files.bat
        # Logs appear out of sequence on Windows. Give time to catch up.
        - sleep 5
        - ls -l library/error.c library/version_features.c programs/psa/psa_constant_names_generated.c programs/test/query_config.c tests/suites/test_suite_psa_crypto_not_supported.generated.data tests/suites/test_suite_psa_crypto_storage_format.current.data tests/suites/test_suite_psa_crypto_storage_format.v0.data
        - for x in library/error.c library/version_features.c programs/psa/psa_constant_names_generated.c programs/test/query_config.c tests/suites/test_suite_psa_crypto_not_supported.generated.data tests/suites/test_suite_psa_crypto_storage_format.current.data tests/suites/test_suite_psa_crypto_storage_format.v0.data; do echo "==== $x ===="; head $x | cat -A; echo; done
        - scripts/windows_msbuild.bat v141 # Visual Studio 2017

after_failure:
- tests/scripts/travis-log-failure.sh

env:
  global:
    - SEED=1
    - secure: "FrI5d2s+ckckC17T66c8jm2jV6i2DkBPU5nyWzwbedjmEBeocREfQLd/x8yKpPzLDz7ghOvr+/GQvsPPn0dVkGlNzm3Q+hGHc/ujnASuUtGrcuMM+0ALnJ3k4rFr9xEvjJeWb4SmhJO5UCAZYvTItW4k7+bj9L+R6lt3TzQbXzg="
